# build map command
uint8 BUILD_MAP_UNKNOWN = 0
uint8 BUILD_MAP_START = 1
uint8 BUILD_MAP_CANCEL = 2
uint8 BUIDL_MAP_FINISH = 3

# Request
uint8 command
string map_name
---
# Response
bool success
string message


# # Build Map
# ros2 service call /build_map san_msgs/srv/BuildMap "{
#   command: 1
# }"

# # Finish Map
# ros2 service call /build_map san_msgs/srv/BuildMap "{
#   command: 3,
#   map_name: 'map_250402'
# }"