float32 voltage_top                 # TOP Battery Voltage (V)        
float32 current_top                 # TOP Battery Current (A)        
float32 soc_top                     # TOP Battery State of Charge    
float32 soh_top                     # TOP Battery State of Health   

float32 voltage                 # Voltage (V)        
float32 current                 # Current (A)        
float32 soc                     # State of Charge    
float32 soh                     # State of Health   
bool    charge_relay            # Charge Relay       
bool    charging_jack_state     # Charging Jack State (True: Other position, False: Home position)
bool    charging_state